version: '3.8'
services:
  api:
    container_name: grid-motors-api
    build: .
    restart: always
    env_file:
      - .env
    volumes:
      - '.:/usr/src/app'
      - /usr/src/app/node_modules
    depends_on:
      - db
    links:
      - db
    ports:
      - '${PORT}:${PORT}'
    command: npm run prod
    environment:
      DATABASE_URI: '${DATABASE_DOCKER_URI}'
      DATABASE_PASSWORD: '${DATABASE_PASSWORD}'
  db:
    image: 'mongo:latest'
    container_name: api-db
    restart: always
    env_file:
      - .env
    ports:
      - '${DATABASE_PORT}:27017'
    volumes:
      - 'dbdata-volume:/data/db'
    environment:
      MONGO_INITDB_USERNAME: '${DATABASE_USERNAME}'
      MONGO_INITDB_PASSWORD: '${DATABASE_PASSWORD}'
      MONGO_INITDB_DATABASE: '${DATABASE_NAME}'
volumes:
  dbdata-volume: null
